version: 2.1
orbs:
  go: circleci/go@1.7
  gcp-gcr: circleci/gcp-gcr@0.13
  jq: circleci/jq@2

jobs:
  publish:
    docker:
      - image: cimg/python:2.7.17
    steps:
      - jq/install
      - setup_remote_docker
      - gcp-gcr/gcr-auth

      - checkout
      - run: echo 'export SERVICE_VERSION=$(echo $CIRCLE_SHA1 | cut -c -7)' >> $BASH_ENV
      - run: echo 'export SERVICE_NAME=$CIRCLE_PROJECT_REPONAME' >> $BASH_ENV
      - run: docker build --build-arg "SSH_PRIVATE_KEY=$(echo $GITHUB_AUTH_TOKEN | base64 -d)" -t asia.gcr.io/${GOOGLE_PROJECT_ID}/${SERVICE_NAME}:${SERVICE_VERSION} .
      - run: docker push asia.gcr.io/${GOOGLE_PROJECT_ID}/${SERVICE_NAME}:${SERVICE_VERSION}
      - run: gcloud container images add-tag --quiet asia.gcr.io/${GOOGLE_PROJECT_ID}/${SERVICE_NAME}:${SERVICE_VERSION} asia.gcr.io/${GOOGLE_PROJECT_ID}/${SERVICE_NAME}:latest
      - run:
          name: pre-auth github.com
          command: |
            mkdir -p ~/.ssh && \
            touch ~/.ssh/known_hosts && \
            chmod 600 ~/.ssh/known_hosts && \
            ssh-keyscan github.com >> ~/.ssh/known_hosts

      - run:
          name: create .npmrc file
          command: |
            echo "//npm.pkg.github.com/:_authToken=\${GITHUB_AUTH_TOKEN}" > ~/.npmrc
            echo "@dekart-xyz:registry=https://npm.pkg.github.com" >> ~/.npmrc
            
      - run:
          name: clone k8s-config
          command: git clone -b master git@github.com:ridebeam/k8s-config.git appcfg

      - run:
          name: update version in k8s-config
          command: BRANCH_NAME=master appcfg/.circleci/promote.sh

workflows:
  continuous-integration:
    jobs:
      # - lint
      # - unit-test
      # switch from publish to trigger-integration-test, never use both at the same time
      #      - trigger-integration-test:
      - publish:
          # requires:
            # - lint
            # - unit-test
          filters:
            branches:
              only: main
          context:
            - GCP-DevOps
            - CircleCI
            - github
